window.PROMPT_EMPIRE_CONFIG = {
  brand: "Prompt Empire™",
  supportEmail: "support@example.com",
  currency: "USD",
  backendUrl: "",
  ownerApiKey: "",
  storeUrl: "",
  attributionDays: 30,
  stripeLinks: {
    "small-business": "",
    "social-media": "",
    "digital-product": "",
    "cleaning-business": "",
    "beauty-business": "",
    "lash-artist": "",
    "hair-stylist": "",
    "real-estate": "",
    "etsy-seller": "",
    "affiliate-marketing": "",
    "side-hustle": "",
    "saas-builder": "",
    "content-creator": "",
    "tiktok-growth": "",
    "email-marketing": "",
    "sales-closing": "",
    "branding": "",
    "ai-image": "",
    "resume-job-search": "",
    "teacher": "",
    "nursing-student": "",
    "church-marketing": "",
    "trucking-business": "",
    "productivity": "",
    "business-startup": "",
    "business-growth-bundle": "",
    "creator-growth-bundle": "",
    "beauty-business-bundle": "",
    "ultimate-vault": ""
  }
};
